#!/usr/bin/env bash
# Installs nginx on my web-01 server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
sudo service nginx enable
exit 0
