#!/usr/bin/env bash
# This is a script that pings an IP address passed as an argument.

arg=$1
if [ "$arg" == "" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
