#!/usr/bin/env bash
#A Bash script that displays the content of the file /etc/passwd
#script should only display username, user id,Home directory path for the user

while read -r name
do
   echo "$name" | cut -d ":" -f1,4,6
done < /etc/passwd
