#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but prints Hi at 9
a=1
while ((a < 21))
do
	echo $a
	case "$a" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((a++))
done
